{43}{72}"Arkham Version Yo Yo Yo"|(merci qui ?)
{90}{115}Afin de stopper la dégradation|des conditions présentes...
{120}{146}et dans l'intérêt commun,
{165}{185}l'état d'urgence est déclaré|dans ces territoires.
{189}{213}Par décret de Lord Cutler Beckett.
{220}{238}Représentant de Sa Majesté le Roi.
{242}{264}Par décret, en application|de la Loi Martiale,
{266}{288}les prérogatives suivantes|sont amendées:
{296}{304}droit de se rassembler, suspendu.
{319}{381}Droit d'Habeas Corpus, suspendu.
