#!/bin/bash

ARG=$1
if [ -z $ARG ]
then
	echo "Aucun argument passe"
else
	./build/test__matmul $ARG &&
	./build/test__matmul_B_ji $ARG &&
	./build/test__matmul_ikj $ARG &&
	./build/test__vector $ARG &&
	./build/test__list $ARG &&
	./build/test__add_and_remove $ARG
fi
